# Generated by Django 4.2.11 on 2025-09-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_is_active_order_status_alter_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('eSewa', 'eSewa'), ('Khalti', 'Khalti'), ('cod', 'Cash on Delivery')], default='eSewa', max_length=20),
        ),
    ]
