# Generated by Django 4.2.11 on 2025-09-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
