# Generated by Django 4.2.11 on 2025-09-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_khalti_pidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
